/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Text;
export const LayerId = IDL.Nat;
export const IngestCategoryId = IDL.Text;
export const StreamTargetId = IDL.Nat;
export const Layer = IDL.Record({
  'id' : LayerId,
  'name' : IDL.Text,
  'size' : IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat }),
  'sourceUrl' : IDL.Text,
  'position' : IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat }),
});
export const Output = IDL.Record({
  'id' : StreamTargetId,
  'ingest_categories' : IDL.Vec(IngestCategoryId),
  'url' : IDL.Text,
  'protocol' : IDL.Text,
  'name' : IDL.Text,
  'stream_key' : IDL.Text,
  'max_bitrate' : IDL.Nat,
});
export const Session = IDL.Record({
  'id' : SessionId,
  'title' : IDL.Text,
  'videoSourceUrl' : IDL.Opt(IDL.Text),
  'layers' : IDL.Vec(LayerId),
  'isActive' : IDL.Bool,
  'outputs' : IDL.Vec(StreamTargetId),
});

export const idlService = IDL.Service({
  'addLayer' : IDL.Func(
      [SessionId, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [LayerId],
      [],
    ),
  'addOutput' : IDL.Func(
      [
        SessionId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IngestCategoryId),
      ],
      [StreamTargetId],
      [],
    ),
  'createSession' : IDL.Func([SessionId, IDL.Text], [], []),
  'getLayer' : IDL.Func([LayerId], [Layer], ['query']),
  'getOutput' : IDL.Func([StreamTargetId], [Output], ['query']),
  'getSession' : IDL.Func([SessionId], [Session], ['query']),
  'listActiveSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'listOutputsByCategory' : IDL.Func(
      [IngestCategoryId],
      [IDL.Vec(Output)],
      ['query'],
    ),
  'setVideoSource' : IDL.Func([SessionId, IDL.Text], [], []),
  'startSession' : IDL.Func([SessionId], [], []),
  'stopSession' : IDL.Func([SessionId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Text;
  const LayerId = IDL.Nat;
  const IngestCategoryId = IDL.Text;
  const StreamTargetId = IDL.Nat;
  const Layer = IDL.Record({
    'id' : LayerId,
    'name' : IDL.Text,
    'size' : IDL.Record({ 'height' : IDL.Nat, 'width' : IDL.Nat }),
    'sourceUrl' : IDL.Text,
    'position' : IDL.Record({ 'x' : IDL.Nat, 'y' : IDL.Nat }),
  });
  const Output = IDL.Record({
    'id' : StreamTargetId,
    'ingest_categories' : IDL.Vec(IngestCategoryId),
    'url' : IDL.Text,
    'protocol' : IDL.Text,
    'name' : IDL.Text,
    'stream_key' : IDL.Text,
    'max_bitrate' : IDL.Nat,
  });
  const Session = IDL.Record({
    'id' : SessionId,
    'title' : IDL.Text,
    'videoSourceUrl' : IDL.Opt(IDL.Text),
    'layers' : IDL.Vec(LayerId),
    'isActive' : IDL.Bool,
    'outputs' : IDL.Vec(StreamTargetId),
  });
  
  return IDL.Service({
    'addLayer' : IDL.Func(
        [SessionId, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [LayerId],
        [],
      ),
    'addOutput' : IDL.Func(
        [
          SessionId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IngestCategoryId),
        ],
        [StreamTargetId],
        [],
      ),
    'createSession' : IDL.Func([SessionId, IDL.Text], [], []),
    'getLayer' : IDL.Func([LayerId], [Layer], ['query']),
    'getOutput' : IDL.Func([StreamTargetId], [Output], ['query']),
    'getSession' : IDL.Func([SessionId], [Session], ['query']),
    'listActiveSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'listOutputsByCategory' : IDL.Func(
        [IngestCategoryId],
        [IDL.Vec(Output)],
        ['query'],
      ),
    'setVideoSource' : IDL.Func([SessionId, IDL.Text], [], []),
    'startSession' : IDL.Func([SessionId], [], []),
    'stopSession' : IDL.Func([SessionId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };