/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type IngestCategoryId = string;
export interface Layer {
  'id' : LayerId,
  'name' : string,
  'size' : { 'height' : bigint, 'width' : bigint },
  'sourceUrl' : string,
  'position' : { 'x' : bigint, 'y' : bigint },
}
export type LayerId = bigint;
export interface Output {
  'id' : StreamTargetId,
  'ingest_categories' : Array<IngestCategoryId>,
  'url' : string,
  'protocol' : string,
  'name' : string,
  'stream_key' : string,
  'max_bitrate' : bigint,
}
export interface Session {
  'id' : SessionId,
  'title' : string,
  'videoSourceUrl' : [] | [string],
  'layers' : Array<LayerId>,
  'isActive' : boolean,
  'outputs' : Array<StreamTargetId>,
}
export type SessionId = string;
export type StreamTargetId = bigint;
export interface _SERVICE {
  'addLayer' : ActorMethod<
    [SessionId, string, string, bigint, bigint, bigint, bigint],
    LayerId
  >,
  'addOutput' : ActorMethod<
    [
      SessionId,
      string,
      string,
      string,
      string,
      bigint,
      Array<IngestCategoryId>,
    ],
    StreamTargetId
  >,
  'createSession' : ActorMethod<[SessionId, string], undefined>,
  'getLayer' : ActorMethod<[LayerId], Layer>,
  'getOutput' : ActorMethod<[StreamTargetId], Output>,
  'getSession' : ActorMethod<[SessionId], Session>,
  'listActiveSessions' : ActorMethod<[], Array<Session>>,
  'listOutputsByCategory' : ActorMethod<[IngestCategoryId], Array<Output>>,
  'setVideoSource' : ActorMethod<[SessionId, string], undefined>,
  'startSession' : ActorMethod<[SessionId], undefined>,
  'stopSession' : ActorMethod<[SessionId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];