/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Session {
    id: SessionId;
    title: string;
    videoSourceUrl?: string;
    layers: Array<LayerId>;
    isActive: boolean;
    outputs: Array<StreamTargetId>;
}
export type LayerId = bigint;
export type StreamTargetId = bigint;
export type SessionId = string;
export type IngestCategoryId = string;
export interface Output {
    id: StreamTargetId;
    ingest_categories: Array<IngestCategoryId>;
    url: string;
    protocol: string;
    name: string;
    stream_key: string;
    max_bitrate: bigint;
}
export interface Layer {
    id: LayerId;
    name: string;
    size: {
        height: bigint;
        width: bigint;
    };
    sourceUrl: string;
    position: {
        x: bigint;
        y: bigint;
    };
}
export interface backendInterface {
    addLayer(sessionId: SessionId, name: string, sourceUrl: string, x: bigint, y: bigint, width: bigint, height: bigint): Promise<LayerId>;
    addOutput(sessionId: SessionId, name: string, protocol: string, url: string, stream_key: string, max_bitrate: bigint, ingest_categories: Array<IngestCategoryId>): Promise<StreamTargetId>;
    createSession(sessionId: SessionId, title: string): Promise<void>;
    getLayer(id: LayerId): Promise<Layer>;
    getOutput(id: StreamTargetId): Promise<Output>;
    getSession(id: SessionId): Promise<Session>;
    listActiveSessions(): Promise<Array<Session>>;
    listOutputsByCategory(categoryId: IngestCategoryId): Promise<Array<Output>>;
    setVideoSource(sessionId: SessionId, videoSourceUrl: string): Promise<void>;
    startSession(id: SessionId): Promise<void>;
    stopSession(id: SessionId): Promise<void>;
}
import type { LayerId as _LayerId, Session as _Session, SessionId as _SessionId, StreamTargetId as _StreamTargetId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addLayer(arg0: SessionId, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint): Promise<LayerId> {
        if (this.processError) {
            try {
                const result = await this.actor.addLayer(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLayer(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addOutput(arg0: SessionId, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: Array<IngestCategoryId>): Promise<StreamTargetId> {
        if (this.processError) {
            try {
                const result = await this.actor.addOutput(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addOutput(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createSession(arg0: SessionId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0, arg1);
            return result;
        }
    }
    async getLayer(arg0: LayerId): Promise<Layer> {
        if (this.processError) {
            try {
                const result = await this.actor.getLayer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLayer(arg0);
            return result;
        }
    }
    async getOutput(arg0: StreamTargetId): Promise<Output> {
        if (this.processError) {
            try {
                const result = await this.actor.getOutput(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOutput(arg0);
            return result;
        }
    }
    async getSession(arg0: SessionId): Promise<Session> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_Session_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_Session_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async listActiveSessions(): Promise<Array<Session>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveSessions();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveSessions();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOutputsByCategory(arg0: IngestCategoryId): Promise<Array<Output>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOutputsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOutputsByCategory(arg0);
            return result;
        }
    }
    async setVideoSource(arg0: SessionId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setVideoSource(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setVideoSource(arg0, arg1);
            return result;
        }
    }
    async startSession(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startSession(arg0);
            return result;
        }
    }
    async stopSession(arg0: SessionId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.stopSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.stopSession(arg0);
            return result;
        }
    }
}
function from_candid_Session_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Session): Session {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    title: string;
    videoSourceUrl: [] | [string];
    layers: Array<_LayerId>;
    isActive: boolean;
    outputs: Array<_StreamTargetId>;
}): {
    id: SessionId;
    title: string;
    videoSourceUrl?: string;
    layers: Array<LayerId>;
    isActive: boolean;
    outputs: Array<StreamTargetId>;
} {
    return {
        id: value.id,
        title: value.title,
        videoSourceUrl: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.videoSourceUrl)),
        layers: value.layers,
        isActive: value.isActive,
        outputs: value.outputs
    };
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Session>): Array<Session> {
    return value.map((x)=>from_candid_Session_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
